<a href="https://colab.research.google.com/github/Humaafroz/Internship-Projects/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
dataset=pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
dataset

In [ ]:
dataset.corr()

User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000

In [ ]:
dataset.drop(['User ID','Gender'],inplace=True,axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(dataset.drop('Purchased',axis=1))

In [ ]:
scaled_features=scaler.transform(dataset.drop('Purchased',axis=1))

In [ ]:
scaled_features

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [ ]:
df=pd.DataFrame(scaled_features,columns=['Age','EstimatedSalary'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(df,dataset['Purchased'],test_size=0.30,random_state=60)

In [ ]:
x_train.shape

(280, 2)

In [ ]:
x_test.shape

(120, 2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
DTC=DecisionTreeClassifier()

In [ ]:
DTC.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
pred=DTC.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,pred))

[[78  4]
 [15 23]]


In [ ]:
((78+24)/120)*100

85.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
classifier=SVC()

In [ ]:
classifier.fit(x_train,y_train)

SVC()

In [ ]:
pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
acc=accuracy_score(y_test,pred)

In [ ]:
acc

0.8916666666666667

In [ ]:
acc*100

89.16666666666667

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc=RandomForestClassifier(n_estimators=100)

In [ ]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
rfc_pred=rfc.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,pred))

[[75  7]
 [ 6 32]]


In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
GNB=GaussianNB()

In [ ]:
GNB.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=GNB.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred)

In [ ]:
acc

0.8833333333333333

In [ ]:
acc*100

88.33333333333333